location = /ALKASH-TRANS {
  return 301 /ALKASH-TRANS/;
}

location ^~ /ALKASH-TRANS/ {
  rewrite ^/ALKASH-TRANS/(.*)$ /$1 break;
  root /var/www/alkash-trans-site;
  try_files $uri $uri/ /index.html;
}
